backend:
  name: git-gateway

media_folder: "images/uploads"
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "homepage"
        file: "content/homepage.json"
        extension: "json"
        description: "Home Page Content"
        fields:
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - {
              label: "Value Prop Title",
              name: "value_prop_title",
              widget: "string",
            }
          - {
              label: "Value Prop Paragraph",
              name: "value_prop_paragraph",
              widget: "text",
            }
          - label: "Enhancements & Add-ons"
            name: "add_ons"
            widget: "list"
            fields:
              - { label: "Add-on Title", name: "title", widget: "string" }
              - {
                  label: "Add-on Description",
                  name: "description",
                  widget: "text",
                }
          - label: "Reviews"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Review Text", name: "text", widget: "text" }
              - { label: "Review Author", name: "author", widget: "string" }
              - { label: "Review Link URL", name: "link", widget: "string" }
              - { label: "Review Source", name: "source", widget: "string" }

      - label: "Services Page"
        name: "servicespage"
        file: "content/servicespage.json"
        extension: "json"
        description: "Serives Page Content"
        fields:
          - label: "Pricing Options"
            name: "prices"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
          - label: "Pricing Notes"
            name: "pricingNotes"
            widget: "list"
            fields:
              - { label: "Description", name: "description", widget: "text" }
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
      - label: "About Page"
        name: "aboutpage"
        file: "content/aboutpage.json"
        extension: "json"
        description: "About Page Content"
        fields:
          - { label: "About Us Copy", name: "aboutCopy", widget: "text" }
          - {
              label: "URL to License",
              name: "licenseAddress",
              widget: "string",
            }
          - { label: "Address", name: "address", widget: "text" }
          - label: "Team"
            name: "team"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Portrait", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Hours"
            name: "hours"
            widget: "list"
            fields:
              - { label: "Day", name: "day", widget: "string" }
              - { label: "Hours", name: "hours", widget: "string" }
  - label: "General Content"
    name: "globalContent"
    files:
      - label: "Social Links"
        name: "socialLinks"
        file: "content/sociallinks.json"
        extension: "json"
        description: "Social media links for the site footer"
        fields:
          - {
              label: "Facebook Link",
              name: "facebookAddress",
              widget: "string",
            }
          - {
              label: "Instagram Link",
              name: "instagramAddress",
              widget: "string",
            }
          - { label: "Twitter Link", name: "twitterAddress", widget: "string" }
          - { label: "YouTube Link", name: "youtubeAddress", widget: "string" }
