backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "homepage"
        file: "content/homepage.json"
        extension: "json"
        description: "Home Page Content"
        fields:
          - {
              label: "Value Prop Title",
              name: "value_prop_title",
              widget: "string",
            }
          - {
              label: "Value Prop Paragraph",
              name: "value_prop_paragraph",
              widget: "text",
            }
          - label: "Enhancements & Add-ons"
            name: "add_ons"
            widget: "list"
            fields:
              - { label: "Add-on Title", name: "title", widget: "string" }
              - {
                  label: "Add-on Description",
                  name: "description",
                  widget: "string",
                }
          - label: "Reviews"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Review Text", name: "text", widget: "string" }
              - { label: "Reviewer Name", name: "name", widget: "string" }
              - { label: "Review Link URL", name: "link", widget: "string" }
              - { label: "Review Source", name: "source", widget: "string" }
