backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "homepage"
        file: "content/homepage.json"
        extension: "json"
        description: "Home Page Content"
        fields:
          - {
              label: "Value Prop Title",
              name: "value_prop_title",
              widget:"string",
            }
          - {
              label: "Value Prop Paragraph",
              name: "value_prop_paragraph",
              widget:"string",
            }
